# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'lishu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lishu
  
  pod "YYModel"
  pod "Masonry"
  pod "FMDB"
  pod 'WMPageController', '~> 2.4.0'
#  pod 'Toast', '~> 4.0.0'
#  pod 'SwiftyStoreKit'
  pod 'ProgressHUD', :path => './ProgressHUD'
  pod 'SnapKit', '~> 5.6.0'
#  pod 'GRDB.swift'
  pod 'libwebp'
#  pod 'iOS-WebP'
  
  pod 'Kingfisher'
  pod 'SwiftyStoreKit'
#  pod 'ObjectMapper'
  
  pod 'CropViewController'
  pod 'CryptoSwift'
  
#  pod 'PhoneNumberKit', '~> 3.7'


end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
    end
end
